# .github/workflows/release-please.yml
name: release-please
on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
#       - uses: google-github-actions/release-please-action@v3
#         with:
#           token: ${{ secrets.TOKEN }}
# #          command: manifest
#           # config-file: release-please-config.json
#           # manifest-file: .release-please-manifest.json
#           release-type: node
#           monorepo-tags: true

      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.TOKEN }}
#          command: manifest
          # config-file: release-please-config.json
          # manifest-file: .release-please-manifest.json
          release-type: node
          monorepo-tags: true
        working-directory: ./hobbies