# .github/workflows/release-please.yml
name: release-please
on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Install release-please client
        run: npm i release-please -g
      - name: Create github release
        run: release-please github-release --token=${{ secrets.TOKEN }} --repo-url=terovirtanen/test-release-please-action
