# .github/workflows/release-please.yml
name: release-please
on: 
  push:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Install release-please client
        run: npm i release-please -g
      # set extra label to ensure correct pr generation (menifest merge issue)
      - name: Create release pr
        run: |
          if [ -n "${{ github.event.release.tag_name }}" ]; then
            LABEL="--label ${{ github.event.release.tag_name }}"
            echo $LABEL
          fi

          release-please release-pr --token=${{ secrets.TOKEN }} --repo-url=terovirtanen/test-release-please-action $LABEL
      - name: Create github release
        run: release-please github-release --token=${{ secrets.TOKEN }} --repo-url=terovirtanen/test-release-please-action
